# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GORUCO 2018
email:
description: > # this means to ignore newlines until "baseurl:"
  GORUCO is a single day, single track conference taking place on Saturday, June 16th 2018 in New York City.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://goruco.com" # the base hostname & protocol for your site
url: "http://www.goruco.com" # the base hostname & protocol for your site
twitter_username: goruco
github_username:  goruco

permalink: /:year/:title

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
